version: "3.9"

services:
  moviematchbackend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SECRET = 123456789
      - URI = mongodb+srv://admin:L6ipkDKepRVkHNUM@clustermoviematch.bjzmi.mongodb.net/?retryWrites=true&w=majority&appName=ClusterMovieMatch
